### ISSUE TITLE
Update roles for GA and TH

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/openproducer-platform#34]
Use this field to describe the task:

Update the roles for @gusaus and @majick777  to "Maintain" which allows write access to repo.

**Comment by tonyzeoli** [comment]
@majick777 Please check to make sure you've been granted write access to the repo.

**Comment by gusaus** [comment]
Thanks, Tony for providing this!

**Comment by gusaus** [comment]
@majick777 Are we good here? If yes I guess we can close out this issue?
